### ISSUE TITLE
Add file operation functions

### ISSUE THREAD

**Issue by arthur-shaw** [arthur-shaw/susoflows#7]
# Objective 🎯

Add file operation

# User stories 📇

After a user downloads SuSo data, there are several other operations that need to occur and that, currently, need to come from hand-crafted code:

- Delete files from previous download
- Unpack zip files into appropriately named folders
- Combine data files
  - Combine value labels
  - Signal incompatibilites (e.g. conflicting variable and/or value labels)
- Write combined data frames to disk

# Tasks ⚙️

Write functions to:

- [ ] Delete old files
- [ ] Unpack zip files
- [ ] Combine value labels
- [ ] Signal incompatibilities in labels and in structure of files
- [ ] Combine data frames
- [ ] Write data frames to disk in user-specified format (i.e., SPSS or Stata)

## Documentation ✍️ 

- [ ] Create section in reference index page
- [ ] Write vignette on working with [AREA]
